# CURRENT_UID=$(id -u):$(id -g) docker-compose --project-name "common-voice" up
# [Running cron jobs in a Docker Alpine container](https://devopsheaven.com/cron/docker/alpine/linux/2017/10/30/run-cron-docker-alpine.html)

version: '3'
services:

  db:
    container_name: db
    image: mysql:5.7.28
    networks:
      - voice-web
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - voice-web

  s3proxy:
    container_name: s3proxy
    # https://github.com/gaul/s3proxy
    image: andrewgaul/s3proxy
    container_name: s3proxy
    ports:
      - 9001:80
    networks:
      - voice-web
    environment:
      - S3PROXY_AUTHORIZATION=none

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/Dockerfile
    links:
      - db
      - redis
    volumes:
      - .:/code
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 8070:9000
    command: bash -c "/code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn && yarn start"
    user: ${CURRENT_UID}

  tasks:
    container_name: tasks
    build:
      context: ./docker/tasks/
      dockerfile: Dockerfile
    depends_on:
      - s3proxy
    networks:
      - voice-web
    command: crond -f -l 8
    env_file:
      - .env-tasks
    volumes:
      - ./docker/tasks/cron_tasks_folder/15min:/etc/periodic/15min/:ro
      - ./docker/tasks/cron_tasks_folder/hourly:/etc/periodic/hourly/:ro


networks:
  voice-web:
