# CURRENT_UID=$(id -u):$(id -g) docker-compose --project-name "common-voice" up

version: '3'
services:
  db:
    image: mysql:5.7.28
    networks:
      - voice-web
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - voice-web

  s3proxy:
    image: andrewgaul/s3proxy
    container_name: s3proxy
    ports:
      - 9001:80
    networks:
      - voice-web
    environment:
      - S3PROXY_AUTHORIZATION=none

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
      - redis
    volumes:
      - .:/code
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 9000:9000
    command: bash -c "/code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn && yarn start"
    user: ${CURRENT_UID}

  audio_backup:
    container_name: audio_backup
    build:
      context: ./docker/tasks/audio_backup
      dockerfile: Dockerfile
    depends_on:
      - s3proxy
    networks:
      - voice-web
    command: crond -f -l 8
    env_file:
      - .env-tasks
      - .env-local-docker  # Using CV_S3_CONFIG
    volumes:
      - ./docker/tasks/audio_backup/cron_tasks/15min:/etc/periodic/15min/:ro
      - ./docker/tasks/audio_backup/cron_tasks/hourly:/etc/periodic/hourly/:ro
    user: ${CURRENT_UID}


  database_backup:
    container_name: database_backup
    build:
      context: ./docker/tasks/database_backup
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - voice-web
    command: crond -f -l 8
    env_file:
      - .env-tasks
      - .env-local-docker  # Using CV_S3_CONFIG
    volumes:
      - ./docker/tasks/database_backup/cron_tasks/15min:/etc/periodic/15min/:ro
      - ./docker/tasks/database_backup/cron_tasks/hourly:/etc/periodic/hourly/:ro
    user: ${CURRENT_UID}


networks:
  voice-web:
